site_name: 我的文档
site_description: 帮助文档
site_author: Roger
site_favicon: favicon.ico

copyright: By Roger
nav:
- 主页: 'index.md'
- 博客:
    - '第一篇': blogs/index1.md
    - '第二篇': blogs/index2.md
    - '第三篇': ['blogs/index01.md', 'blogs/index02.md']
- 消息中心: 'msgcenterHelps.md'
- 关于: 'about.md'
# pages:
# - ['index.md', '主页']
# - ['blogs/index.md', 'User Guide', 'Creating a new Mashmallow project']
# - ['blogs/index2.md', 'User Guide', 'Mashmallow API guide']
# - ['blogs/index3.md', 'User Guide', 'Configuring Mashmallow']
# - ['aboutlove.html', 'About', 'License']
theme: 'mkdocs'
